### ISSUE TITLE
Broken mail link for individual student profiles.

### ISSUE THREAD

**Issue by dcarrot2** [briandeanda/CSin3Students#51]
When I navigate to a student profile and click on the mailing icon, I am routed to /currentStudents/studentemail@csumb.edu.

This should be changed to a mailto link. I believe that is the standard norm for mail links. At least from what I've seen around.

Requires: Changes to the frontend.

**Comment by artLopez** [comment]
I agree with you. When I was developing on Scoreboard I saw `mailto` as well.

**Comment by dcarrot2** [comment]
Closed by #52 .
